# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-04 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acudiente',
            table='acudiente',
        ),
    ]
