# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-04 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0002_auto_20170504_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acudiente',
            options={},
        ),
    ]
