# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-16 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0003_auto_20170504_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acudiente',
            options={'managed': False},
        ),
    ]
