# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-16 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acudiente', '0004_auto_20170516_1310'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acudiente',
            table='Acudiente',
        ),
    ]
