# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Acudiente',
            },
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Alimentacion',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Dia',
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Ejercicio',
            },
        ),
        migrations.CreateModel(
            name='EstadoPerruno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Estado_perruno',
            },
        ),
        migrations.CreateModel(
            name='HorarioDieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo_dieta', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Horario_dieta',
            },
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('edad', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'Madre',
            },
        ),
        migrations.CreateModel(
            name='NivelEntrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('tiempo_entrenamiento', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'Nivel_entrenamiento',
            },
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('edad', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'Padre',
            },
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=1)),
                ('peso', models.IntegerField()),
                ('estado_salud', models.TextField()),
                ('fecha_desparasitacion', models.DateField(blank=True, null=True)),
                ('epoca_celo_aproximada', models.DateField(blank=True, null=True)),
                ('epoca_celo_real', models.DateField(blank=True, null=True)),
                ('condiciones_prestamo', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Perro',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Raza',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('tiempo_estadia', models.IntegerField()),
                ('precio_aproximado', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Suplemento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('marca', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Suplemento',
            },
        ),
        migrations.CreateModel(
            name='Tamanio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Tamanio',
            },
        ),
        migrations.CreateModel(
            name='TipoReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Tipo_reserva',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'Vacuna',
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('telefono', models.TextField()),
                ('direccion', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Veterinario',
            },
        ),
    ]
